# Generated by Django 5.2.3 on 2025-06-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_userprofile_age_userprofile_date_of_birth_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="date_of_birth",
            new_name="dob",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="balance",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="mobile",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
